### ISSUE TITLE
Fahrenheit Support? 

### ISSUE THREAD

**Issue by Mertzenich** [Lacerte/clima#11]
Is there support for Fahrenheit in the app (installed from f-droid)? If not I'd appreciate it being added.

**Comment by prestosole** [comment]
Hello @Mertzenich, Thanks for using our app. We are indeed working on adding Fahrenheit support in the next update (v1.2).

**Comment by Mertzenich** [comment]
> Hello @Mertzenich, Thanks for using our app. We are indeed working on adding Fahrenheit support in the next update (v1.2).

Thank you! This is one of the better weather apps. Insatiably all other simple weather apps get bloated.

**Comment by triallax** [comment]
Closing in favor of #17, because it is more general (e.g. it includes using miles instead of kilometers).
