### ISSUE TITLE
Add support for imperial units

### ISSUE THREAD

**Issue by triallax** [Lacerte/clima#17]

**Comment by PrestoSole** [comment]
Closed in favor of #29

**Comment by triallax** [comment]
So here's how I imagine this might be implemented:

- Add a `UnitSystem` enum in `clima_domain`, which would look something like this:
  ```dart
  enum UnitSystem { metric, imperial }
  ```
- Add a new method `withUnitSystem` (the method name isn't important, we can change it later if needed) to `FullWeather` and related classes (e.g. `Weather` and `HourlyForecast`), which takes `UnitSystem` as an argument and returns a new instance of the corresponding class, with the values changed accordingly (e.g. meters will become feet).

- The above entails adding a `unitSystem` property to the classes I mentioned above so we know what system the values are using.

- In `clima_ui` just add a unit system setting and then use the `withUnitSystem` method in the weather screen to display the weather data in the appropriate unit system.
