### ISSUE TITLE
5 Days forecast not showing

### ISSUE THREAD

**Issue by dhishkyaon** [Lacerte/clima#184]
I can only see the real time weather conditions. 5 days forecast is not available as shown in the screenshots.

**Comment by prestosole** [comment]
Hi @hellyeahmfs. What's shown in the README is version 2.0 of the app (still not completed yet). The one on F-droid is version 1.2.1. You can, however, try out the updated yet not completed version by compiling from source or by downloading this [APK](https://github.com/Lacerte/clima/files/7006630/app-release.zip) (current master).

**Comment by dhishkyaon** [comment]
OK gotcha!
