### ISSUE TITLE
Make the app icon adaptive

### ISSUE THREAD

**Issue by robotwombat** [Lacerte/clima#299]
**Is your feature request related to a problem? Please describe.**
Currently, the app icon isn't adaptive, meaning it is placed on a white background:
![Screenshot_20220509-144301_Quickstep](https://user-images.githubusercontent.com/44946401/167423276-b52426bf-630e-44e8-8835-f5238ecb21d1.png)

**Describe the solution you'd like**
Implement adaptive icon support:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

It would look something like this mockup
![Screenshot_20220509-144647_Quickstep](https://user-images.githubusercontent.com/44946401/167424045-738fb368-be62-4019-8f8f-79c4ef902e7f.png)

Thanks!!

**Comment by prestosole** [comment]
LGTM! I'm looking forward into implementing this in the next feature update.

**Comment by robotwombat** [comment]
> LGTM! I'm looking forward into implementing this in the next feature update.

Fantastic :)
Thanks!
