### ISSUE TITLE
Weather Alert Notifications

### ISSUE THREAD

**Issue by prestosole** [Lacerte/clima#31]

**Comment by triallax** [comment]
What does this mean? Can you explain a bit more?

**Comment by prestosole** [comment]
Push alerts and notifications on weather changes (probably serious ones).

**Comment by triallax** [comment]
That's gonna be a bit difficult to do I think, and it won't be reliable unless we use Google Push Services or something like that. Take that with a grain of salt though until I research this a bit more.

**Comment by prestosole** [comment]
OpenWeatherMap already has an API call for it.

Here is the link: https://openweathermap.org/api/push-weather-alerts

**Comment by triallax** [comment]
Well, will our app be constantly running in the background listening to the notification? Probably not.

**Comment by triallax** [comment]
Also, apparently, it costs $125/month.

**Comment by prestosole** [comment]
The API doesn't include all countries. Hmm.. leave that for a later discussion? Or abandon the idea?

**Comment by triallax** [comment]
I think it not including all countries is fine, but the cost in addition to the fact that this will hasten the inevitability of reaching the API rate limiting makes this not worth it in my opinion.

**Comment by prestosole** [comment]
You have a good point.
