### ISSUE TITLE
App labels tomorrow as "Today" and today as the day name

### ISSUE THREAD

**Issue by betsythefc** [Lacerte/clima#317]
**Describe the bug**
App labels tomorrow as "Today" and today as the day name

**To Reproduce**
1. View weather screen

**Expected behavior**
Today should say "Today" and tomorrow should be the day name

**Screenshots**
This screenshot was taking on Wednesday, 2022-06-08 (yesterday).
![2022-06-08 Clima, Day naming error, Redacted](https://user-images.githubusercontent.com/15450365/172898788-186b4ccf-e619-42bb-b33f-639be7feca9f.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Flip 3 5G
 - OS: Android 12
 - App version: 2.0.1 F-Droid

**Comment by triallax** [comment]
Reproduced. I'm fairly sure this has to do with wrong handling of timezones somewhere in the code.
